[deployment]
hostname = "localhost"
node_ip = "10.100.1.80"

enable_mtom = false # optional
enable_swa = false # optional

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[transport.http] # Optional
socket_timeout_millis = 180000
protocol = "http" # inferred

listener.port = 8280
listener.wsdl_epr_prefix = "https://apachehost:port/somepath"
listener.hostname = "$conf{deployement.node_ip}" # inferred

listener.secured_port = 8243
listener.secured_protocols = "TLSv1,TLSv1.1,TLSv1.2" # inferred
listener.secured_wsdl_epr_prefix = "https://apachehost:port/somepath"

listener.keystore.file_name ="$conf{keystore.tls.file_name}" # inferred
listener.keystore.type = "$conf{keystore.tls.type}" # inferred
listener.keystore.password = "$conf{keystore.tls.password}" # inferred
listener.keystore.key_password = "$conf{keystore.tls.key_password}" # inferred

listener.truststore.file_name = "$conf{truststore.file_name}" # inferred
listener.truststore.type = "$conf{truststore.tls.type}" # inferred
listener.truststore.password = "$conf{truststore.tls.password}" # inferred

sender.warn_on_http_500 = "*"
sender.proxy_hostname = "${deployement.node_ip}"
sender.proxy_port = 3128
sender.non_proxy_hostnames = "localhost|moon|sun"

sender.keystore.file_name ="$conf{keystore.tls.file_name}" # inferred
sender.keystore.type = "$conf{keystore.tls.type}" # inferred
sender.keystore.password = "$conf{keystore.tls.password}" # inferred
sender.keystore.key_password = "$conf{keystore.tls.key_password}" # inferred

sender.truststore.file_name = "$conf{truststore.file_name}" # inferred
sender.truststore.type = "$conf{truststore.tls.type}" # inferred
sender.truststore.password = "$conf{truststore.tls.password}" # inferred

blocking_sender.enable_client_caching = true
blocking_sender.enable_client_caching = true
blocking_sender.transfer_encoding = "chunked"
blocking_sender.default_connections_per_host = 200
blocking_sender.omit_soap12_action = true

[[custom_transport]]
class="<qualified class name>"
protocol = "ISO8583"
parameter.port = 8081
parameter.hostname = "$conf{deployment.node_ip}"

[transport.local] # Optional
    type = "NonBlockingLocalTransport"

[transport.vfs] # enable by default
listener.enable = true
sender.enable = true

[transport.mail] # optional
listener.enable = true

sender.hostname = "smtp.gmail.com"
sender.port = 587
sender.enable_tls = true
sender.auth = true
sender.username = "demo_user"
sender.password = "mailpassword"
sender.from = "demo_user@wso2.com"

[transport.fix] # optional
listener.enable = true
listener.class = "org.apache.synapse.transport.fix.FIXTransportListener" # inferred

sender.enable = true
sender.class = "org.apache.synapse.transport.fix.FIXTransportSender" # inferred

[[transport.jms.listener]]
name = "myTopicListener"
parameter.initial_naming_factory = "org.apache.activemq.artemis.jndi.ActiveMQInitialContextFactory"
parameter.broker_name = "artemis"
parameter.provider_url = "tcp://localhost:61616"
parameter.connection_factory_name = "TopicConnectionFactory"
parameter.connection_factory_type = "topic" # [queue, topic]
parameter.cache_level = "consumer"

[[transport.jms.sender]]
name = "myTopicSender"
parameter.initial_naming_factory = "org.apache.activemq.artemis.jndi.ActiveMQInitialContextFactory"
parameter.broker_name = "artemis"
parameter.provider_url = "tcp://localhost:61616"
parameter.connection_factory_name = "TopicConnectionFactory"
parameter.connection_factory_type = "topic"
parameter.cache_level = "producer"

[transport.hl7] # optional
listener.enable = true
listener.port = 9292 # inferred
listener.class = "org.wso2.carbon.business.messaging.hl7.transport.HL7TransportListener" # inferred

sender.enable = true
sender.non_blocking = true # inferred
sender.class = "org.wso2.carbon.business.messaging.hl7.transport.HL7TransportSender" # inferred

[transport.sap] # optional
listener.enable = true
listener.idoc.class = "org.wso2.carbon.transports.sap.SAPTransportListener" # inferred
listener.bapi.class = "org.wso2.carbon.transports.sap.SAPTransportListener" # inferred

sender.enable = true
sender.idoc.class = "org.wso2.carbon.transports.sap.SAPTransportSender" # inferred
sender.bapi.class = "org.wso2.carbon.transports.sap.SAPTransportSender" # inferred

[mediation]
synapse.core_threads = 20
synapse.max_threads = 100
synapse.threads_queue_length = 10

synapse.global_timeout_interval_millis=120000
#In memory statistics cleaning state
statistics.enable_clean=true
statistics.clean_interval_millis=1000

synapse.preserve_namespace_on_xml_to_json=false


# Uncomment following to support fallback XPATH 2.0 support with DOM and Saxon
synapse.enable_xpath_dom_failover=true
synapse.temp_data_chunk_size=3072

#configuration for the external debugger channels if server is started in debug mode
synapse.command_debugger_port=9005
synapse.event_debugger_port=9006

# Script Mediator Pool (impatcts only external scripts)
synapse.script_mediator_pool_size=15

# Configuration to enable mediation flow analytics
mediation.flow.statistics.enable=false
mediation.flow.statistics.capture_all=false

mediation.flow.statistics.tracer.collect_payloads=false
mediation.flow.statistics.tracer.collect_properties=false

mediation.inbound.core_threads = 20
mediation.inbound.max_threads = 100

[user_store]
type = "database"

[database.shared_db]
type = "h2"
url="jdbc:h2:./repository/database/WSO2SHARED_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000"
username = "wso2carbon"
password = "wso2carbon"

[database.shared_db.pool_options]
maxActive = "50"
maxWait = "60000"
testOnBorrow = true
validationInterval = "30000"
defaultAutoCommit = true

[keystore.tls]
file_name = "wso2carbon.jks"
type = "JKS"
password = "wso2carbon"
alias = "wso2carbon"
key_password = "wso2carbon"

[truststore]
file_name = "wso2carbon.jks"
type = "JKS"
password = "wso2carbon"
alias = "symmetric.key.value"
algorithm = "AES"
